import { IsNotEmpty, IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class RegisterDeviceDto {
  @ApiProperty({
    description: 'Unique hardware UUID of the device gateway node',
    example: 'device_dev_1',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    description: 'Human-readable label for the device node',
    example: 'Pixel 5 - SIM1 Gateway',
  })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    description:
      'Cellular phone number associated with the active SIM card (E.164 format)',
    example: '+919876543210',
  })
  @IsString()
  @IsNotEmpty()
  phoneNumber: string;

  @ApiProperty({
    description: 'Cellular network provider or carrier name',
    example: 'Jio',
  })
  @IsString()
  @IsNotEmpty()
  provider: string;

  @ApiProperty({
    description:
      'Cryptographic RSA Public Key generated by the client node for authentication handshakes',
    example: 'mock_rsa_public_key_value',
  })
  @IsString()
  @IsNotEmpty()
  publicKey: string;
}
